# Created by trellis-cli v1.6.1
# Documentation: https://docs.roots.io/trellis/master/wordpress-sites/

wordpress_sites:
  carloslobato.com.br:
    site_hosts:
    - canonical: carloslobato.test
      redirects:
      - www.carloslobato.test
    local_path: ../site
    admin_email: admin@carloslobato.test
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
